In [2]:
import os
os.getcwd()
os.chdir(r"C:\Users\athar\Downloads")

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [6]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
df=pd.read_excel('CDAC_DataBook.xlsx',sheet_name='ERPData') #if you get error do the command pip install openpyxl

In [13]:
df.head(3)

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27

In [9]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [10]:
df.tail()

   MaterialID Location  Quantity
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [12]:
df.shape #give number of rows and columns in data frame

(50, 3)

In [14]:
df.columns #gives the columns

Index(['MaterialID', 'Location', 'Quantity'], dtype='object')

In [15]:
list(df.columns) #gives the cloumn in form of list

['MaterialID', 'Location', 'Quantity']

In [ ]:
df.columns.values[1]="Location" # we can use this command to change the column name, we provide the index of coln to change

In [ ]:
df.Location #extracts a particular column from the data frame

In [ ]:
#in dataframe of python

In [16]:
type(df)

pandas.core.frame.DataFrame

In [18]:
ind=np.where(df.Location=='MWH-2') #this has all the indices of columns where location is mwh-2

In [25]:
df1=df.iloc[ind] #creates df using those indices of rows

In [26]:
df1

   MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85

In [44]:
#either 2 or 4 and quantity more than 75
ind=np.where(((df.Location=='MWH-2' ) | (df.Location=='MWH-4')) &  (df.Quantity>75))
ind
df10=df.iloc[ind].reset_index(drop=True)
df10

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        78
1    TMI-43T    MWH-4        76
2    GCVB-79    MWH-2        87
3    AXCP-78    MWH-2        85

In [52]:
# wh-1 or wh-3 with quantity <50
indx=np.where(((df.Location=='MWH-1')| (df.Location=='MWH-3')) & (df.Quantity<50)) #where is only available in np
df15=df.iloc[indx]
df15

   MaterialID Location  Quantity
10    SDRT-67    MWH-1        34
40    DDBN-89    MWH-1        34
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
47    AXCP-78    MWH-3        29
49    DDBN-89    MWH-1        39

In [41]:
len(df10)

11

In [59]:
min(df.Quantity)

42

In [60]:
ind=np.where(df.Quantity<40) #find the indicies where quantity<40
df11=df.drop(ind[0]) #no where while dropping we drop the indices of rows from 
df11

   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
3     AXCP-78    MWH-5        65
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
19    TMI-43T    MWH-4        52
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
29    LXCV-21    MWH-5        57
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
41    SDRT-67    MWH-1        57
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75

In [68]:
#find sdrt-67
#ind=np.where(df.MaterialID=="SDRT-67")
df17=df.iloc[np.where(df.MaterialID=="SDRT-67")] #single query
df17

   MaterialID Location  Quantity
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31

In [76]:
#name and grade of stud who have done either python or ml python
pune=pd.read_excel('CDAC_DataBook.xlsx',sheet_name='Pune')
ind=np.where((pune.Subject=="Python")| (pune.Subject=='MLPython')) #searching the index that matches the query
pune.iloc[ind[0],[0,1,2]]

     Name   Subject Grade
0  Rakesh    Python     A
1   Manoj  MLPython     C

In [96]:
#where quantity value in min give quantity and name
ind=np.where(df.Quantity==min(df.Quantity)) #to find min save the value in another column
df17=df.iloc[ind[0],[0,1]]
df17

  MaterialID Location
8    GCVB-79    MWH-2

In [100]:
#find min and max
ind=np.where(df.Quantity==min(df.Quantity))

In [3]:
df=pd.read_excel("CDAC_DataBook.xlsx",sheet_name='EmpInfo')
df

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN      NaN  ER534867
6   Deepak   NaN  Quality  RF453432

In [113]:
ind=np.where(df.Deptt.isnull())
ind
ind2=np.where(df.EmpID.isnull())
ind2

(array([5, 6], dtype=int64),)

In [125]:
#one df--> values which are missing , and one df with clean df
ind3=np.where(df.EmpID.isnull() | df.Deptt.isnull()) #either dept or emp id is null

In [122]:
newdf=df.dropna() #drop na values
newdf 

df.isnull() #boolean values of whether na or not
df.isnull().sum() #gives the sum of whether

Name        1
EmpID       2
Deptt       2
Passport    0
dtype: int64

In [129]:
df.Deptt.fillna('Overhead') #fills those to the coln NA ,by writing you mention in '' 
df['NewCol']=df.Deptt.fillna('Overhead') "add new coln and writes in place of null values"

#df.Deptt.fillna("Overhead",inplace=True) #to override the data coln without adding new

In [132]:
x1=np.array([2,4,6,3,np.nan,3,1])
df['Marks']=x1
#we carry out median on the null values to fill the column when coln has intergers
#we carry out mode for column where those are null where it is string

In [133]:
df['Marks']=df.Marks.fillna(df.Marks.median())

In [134]:
df

      Name EmpID    Deptt  Passport    NewCol  Marks
0   Sudeep  A342  Quality  DF453278   Quality    2.0
1  Ruchika  C578    Sales  CA567657     Sales    4.0
2      NaN  J436    Admin  DF453278     Admin    6.0
3    Arjun  A342      NaN  RF453432  Overhead    3.0
4    Rishi  R475    Prodn  DF453278     Prodn    3.0
5   Chetan   NaN      NaN  ER534867  Overhead    3.0
6   Deepak   NaN  Quality  RF453432   Quality    1.0

In [135]:
df.Deptt.fillna(method="ffill") #the value before nan is filled at the place of nan
df.Deptt.fillna(method="bfill") # the value after nan is filled at the place of nan

0    Quality
1      Sales
2      Admin
3      Admin
4      Prodn
5      Prodn
6    Quality
Name: Deptt, dtype: object

In [136]:
df

      Name EmpID    Deptt  Passport    NewCol  Marks
0   Sudeep  A342  Quality  DF453278   Quality    2.0
1  Ruchika  C578    Sales  CA567657     Sales    4.0
2      NaN  J436    Admin  DF453278     Admin    6.0
3    Arjun  A342      NaN  RF453432  Overhead    3.0
4    Rishi  R475    Prodn  DF453278     Prodn    3.0
5   Chetan   NaN      NaN  ER534867  Overhead    3.0
6   Deepak   NaN  Quality  RF453432   Quality    1.0

In [139]:
df.duplicated() #tells whether the values are duplicated ,if nothing is in () it returns for that specific column,this doesnt give when the value occues
#for the first time
df.duplicated("Passport")
np.where(df.duplicated("Passport")) #tells the indices where the values are duplicated

(array([2, 4, 6], dtype=int64),)

In [140]:
np.where(df.Passport.duplicated(keep=False)) #gives the first occurance of the column

(array([0, 2, 3, 4, 6], dtype=int64),)

In [ ]:
np.where(df.Passport.duplicated(keep='first')) #hides first element
np.where(df.Passport.duplicated(keep='last')) #hides last element