In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [4]:
s1=pd.Series([2,3,4,5])

In [7]:
(s1)

0    2
1    3
2    4
3    5
dtype: int64

In [8]:
s1[2] #has index ,occurs in normal way

4

In [9]:
s1[0:3]

0    2
1    3
2    4
dtype: int64

In [11]:
s1=pd.Series([2,3,4,5],index=['A','B','C','D']) #to give the labels that you want to give,this are labels,but still the index will be 0-->...

In [12]:
s1

A    2
B    3
C    4
D    5
dtype: int64

In [13]:
#index based reference
s1.iloc[2]

4

In [15]:
#.iloc is used,when extraction need to be done by index
s1.loc['C']  #to search on the basis of label

4

In [16]:
s2=pd.Series([3,4,5,6],index=[1,2,3,4])

In [17]:
s2

1    3
2    4
3    5
4    6
dtype: int64

In [19]:
s2.iloc[2] #gives element on the index=2

5

In [20]:
s2.loc[2] #gives the element with label=2

4

In [21]:
s1.iloc[[1,3]] #gives the element at index 1,3
#if the element is out of range of array it throws an error

B    3
D    5
dtype: int64

In [26]:
#we can create series out of dictionary, keys will be label and values will be values itself
d1={'A':3,'B':5,'C':8}
s1=pd.Series(d1)

In [38]:
s=pd.Series(d1,index=['B']) #takes only the key with the label given and create a new series
s.keys()[0]#to access keys we can do is s.keys()[index]
#to access the values we can do is s.loc[label]/multiple values [[labels]]

'B'

In [27]:
s1

A    3
B    5
C    8
dtype: int64

In [28]:
s2=pd.Series([4,7],index=['D','E'])

In [31]:
s1=pd.concat([s1,s2])

In [34]:
 #modifying series
s2.iloc[1]=17

In [35]:
s2

D     4
E    17
dtype: int64

In [ ]:
#if we give 'loc' and try to find out the values it gives all the values of the key

In [ ]:
#deleting based on index
s2.drop(s2.index[1])
#deleting on basis of label
s2.drop(['B'])

Dataframe

In [55]:
df1=pd.DataFrame([['A',25,76],['B',45,90],['C',50,97]],columns=['Name','RollNumber','Marks']) #we created list of list
#used to enter data when it is in row format

In [56]:
df1

  Name  RollNumber  Marks
0    A          25     76
1    B          45     90
2    C          50     97

In [46]:
#to insert in column format we provide in form of dictionary
d1={'PlayerName':['Sachin','Dhoni','Kohli'],'Teams':['MI','CSK','RCB']}

In [50]:
df2=pd.DataFrame(d1)

In [51]:
df2

  PlayerName Teams
0     Sachin    MI
1      Dhoni   CSK
2      Kohli   RCB

In [ ]:
#while concatinating the name of the columns should be same, or else it will show the error

In [57]:
df3=pd.concat([df1,df2])

In [58]:
df3

  Name  RollNumber  Marks PlayerName Teams
0    A        25.0   76.0        NaN   NaN
1    B        45.0   90.0        NaN   NaN
2    C        50.0   97.0        NaN   NaN
0  NaN         NaN    NaN     Sachin    MI
1  NaN         NaN    NaN      Dhoni   CSK
2  NaN         NaN    NaN      Kohli   RCB

In [61]:
df4=pd.DataFrame([['H',12,76],['E',15,95]],columns=df1.columns)

In [62]:
pd.concat([df1,df4])

  Name  RollNumber  Marks
0    A          25     76
1    B          45     90
2    C          50     97
0    H          12     76
1    E          15     95

In [66]:
df1.iloc[[1]]
df1.iloc[1]

df1.loc[1]

Name           B
RollNumber    45
Marks         90
Name: 1, dtype: object

In [77]:
newDF=pd.concat([df1,df4]).reset_index(drop=True)
#if we dont take drop =true it will take the column of previous repeating label along with the new one

In [78]:
newDF

  Name  RollNumber  Marks
0    A          25     76
1    B          45     90
2    C          50     97
3    H          12     76
4    E          15     95

In [92]:
x1=[50,80]
df4['Marks2']=x1

In [87]:
df1

  Name  RollNumber  Marks  Marks2
0    A          25     45      45
1    B          45     68      68
2    C          50     34      34

In [85]:
df3.drop([0,2]) #rows with index 0 and 2 are removed

  Name  RollNumber  Marks
0    H          12     76
1    E          15     95

In [96]:
df4.drop('Marks2',axis=1) #removes the column specified and if there are multiple columns we add list of index

  Name  RollNumber  Marks
0    H          12     76
1    E          15     95

In [104]:
df4.drop(df4.columns[1],axis=1) #removes coln with index specified, to remove multiple rows we can insert list in coln part

  Name  Marks
0    H     76
1    E     95

In [105]:
df4.iat[1,2]=60 #using this you can replace a specific cell, iat[row,coln]=new value

In [108]:
df4.at[0,'Marks']=70 #using labels for everything
df4

  Name  RollNumber  Marks  Marks2
0    H          12     70      50
1    E          15     60      80

In [109]:
import os

In [114]:
os.getcwd() #gets current working directory

'C:\\Users\\athar\\Downloads'

In [113]:
os.chdir(r"C:\Users\athar\Downloads") #makes this as current working directory