In [107]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [108]:
import os
os.getcwd()
os.chdir(r"C:\Users\athar\Downloads")

In [109]:
df=pd.read_excel("CDAC_DataBook.xlsx",sheet_name="ERPData")

In [110]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [7]:
grp1=df.groupby('Location') #creates group by in df on basis of location

In [9]:
grp1.groups #shows the various groups

{'MWH-1': [1, 9, 10, 24, 25, 26, 39, 40, 41, 48, 49], 'MWH-2': [2, 7, 8, 15, 35, 36, 42, 45, 46], 'MWH-3': [14, 43, 44, 47], 'MWH-4': [0, 4, 5, 6, 11, 12, 13, 18, 19, 20, 21, 22, 30, 31, 32], 'MWH-5': [3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38]}

In [10]:
grp1.get_group("MWH-2") #gives you the values present in the group "mwh-2"

   MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85

In [18]:
grp1.Quantity.agg(['sum','size']) #aggregates and gives various values by doing summation

          sum  size
Location
MWH-1     889    11
MWH-2     397     9
MWH-3     174     4
MWH-4     728    15
MWH-5     697    11

In [32]:
df2=grp1.agg(np.sum).Quantity #sums the rows based on individual group

In [20]:
df2.shape

(5,)

In [21]:
type(df2)

pandas.core.series.Series

In [24]:
df2=grp1.agg(np.sum).Quantity.reset_index() #to add index value and not giving drop=true in bracket  is because we dont want to exclude location colmn
df2

  Location  Quantity
0    MWH-1       889
1    MWH-2       397
2    MWH-3       174
3    MWH-4       728
4    MWH-5       697

In [25]:
type(df2) #now it is dataframe,BUT LOOK WHY ITS SO

pandas.core.frame.DataFrame

In [26]:
grp1.Quantity.count().reset_index()

  Location  Quantity
0    MWH-1        11
1    MWH-2         9
2    MWH-3         4
3    MWH-4        15
4    MWH-5        11

In [27]:
grp1.Quantity.sum().reset_index()

  Location  Quantity
0    MWH-1       889
1    MWH-2       397
2    MWH-3       174
3    MWH-4       728
4    MWH-5       697

In [28]:
grp1.Quantity.mean().reset_index()

  Location   Quantity
0    MWH-1  80.818182
1    MWH-2  44.111111
2    MWH-3  43.500000
3    MWH-4  48.533333
4    MWH-5  63.363636

In [29]:
grp2=df.groupby(['MaterialID','Location']) #here the first coln is primary key and secondary is second one

In [31]:
grp2.groups

{('AXCP-78', 'MWH-1'): [1, 24, 25, 39, 48], ('AXCP-78', 'MWH-2'): [46], ('AXCP-78', 'MWH-3'): [47], ('AXCP-78', 'MWH-4'): [4], ('AXCP-78', 'MWH-5'): [3, 37, 38], ('DDBN-89', 'MWH-1'): [26, 40, 49], ('DDBN-89', 'MWH-2'): [45], ('DDBN-89', 'MWH-3'): [43], ('DDBN-89', 'MWH-4'): [22, 30], ('DDBN-89', 'MWH-5'): [23], ('GCVB-79', 'MWH-2'): [8, 15, 35, 36], ('GCVB-79', 'MWH-5'): [34], ('LXCV-21', 'MWH-2'): [2], ('LXCV-21', 'MWH-3'): [44], ('LXCV-21', 'MWH-5'): [27, 28, 29], ('SDRT-67', 'MWH-1'): [10, 41], ('SDRT-67', 'MWH-2'): [42], ('SDRT-67', 'MWH-4'): [11], ('SDRT-67', 'MWH-5'): [16, 17], ('TMI-43T', 'MWH-1'): [9], ('TMI-43T', 'MWH-2'): [7], ('TMI-43T', 'MWH-3'): [14], ('TMI-43T', 'MWH-4'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('TMI-43T', 'MWH-5'): [33]}

In [34]:
grp2.agg([np.sum,np.size]) # aggregates on the basis of size and gives sum of quantity

                    Quantity
                         sum size
MaterialID Location
AXCP-78    MWH-1         548    5
           MWH-2          85    1
           MWH-3          29    1
           MWH-4          36    1
           MWH-5         200    3
DDBN-89    MWH-1         130    3
           MWH-2          69    1
           MWH-3          38    1
           MWH-4          75    2
           MWH-5          71    1
GCVB-79    MWH-2         156    4
           MWH-5          26    1
LXCV-21    MWH-2          27    1
           MWH-3          42    1
           MWH-5         174    3
SDRT-67    MWH-1          91    2
           MWH-2          31    1
           MWH-4          58    1
           MWH-5         114    2
TMI-43T    MWH-1         120    1
           MWH-2          29    1
           MWH-3          65    1
           MWH-4         559   11
           MWH-5         112    1

In [35]:
newdf=grp2.agg([np.sum,np.size])

In [38]:
newdf.loc['AXCP-78'] #when grouping on two columns ,it results in the df with multi index

         Quantity
              sum size
Location
MWH-1         548    5
MWH-2          85    1
MWH-3          29    1
MWH-4          36    1
MWH-5         200    3

In [42]:
# we can search any combination of columns depending on the primary key and secondary key we provided during grouping
newdf.loc[[('LXCV-21','MWH-3'),('TMI-43T','MWH-2')]]

                    Quantity
                         sum size
MaterialID Location
LXCV-21    MWH-3          42    1
TMI-43T    MWH-2          29    1

In [44]:
df2=df.sort_values(['Quantity'],ascending=False) #sort on the basis of column provided
df2

   MaterialID Location  Quantity
24    AXCP-78    MWH-1       152
39    AXCP-78    MWH-1       145
9     TMI-43T    MWH-1       120
33    TMI-43T    MWH-5       112
25    AXCP-78    MWH-1       109
17    SDRT-67    MWH-5       102
15    GCVB-79    MWH-2        87
46    AXCP-78    MWH-2        85
27    LXCV-21    MWH-5        83
5     TMI-43T    MWH-4        78
12    TMI-43T    MWH-4        76
48    AXCP-78    MWH-1        75
21    TMI-43T    MWH-4        75
23    DDBN-89    MWH-5        71
38    AXCP-78    MWH-5        70
45    DDBN-89    MWH-2        69
1     AXCP-78    MWH-1        67
14    TMI-43T    MWH-3        65
37    AXCP-78    MWH-5        65
3     AXCP-78    MWH-5        65
31    TMI-43T    MWH-4        65
11    SDRT-67    MWH-4        58
29    LXCV-21    MWH-5        57
41    SDRT-67    MWH-1        57
26    DDBN-89    MWH-1        57
19    TMI-43T    MWH-4        52
22    DDBN-89    MWH-4        48
32    TMI-43T    MWH-4        43
44    LXCV-21    MWH-3        42
49    DDBN-89    MWH-1        39
20    TMI-43T    MWH-4        39
43    DDBN-89    MWH-3        38
4     AXCP-78    MWH-4        36
40    DDBN-89    MWH-1        34
10    SDRT-67    MWH-1        34
28    LXCV-21    MWH-5        34
0     TMI-43T    MWH-4        34
18    TMI-43T    MWH-4        34
13    TMI-43T    MWH-4        32
35    GCVB-79    MWH-2        31
42    SDRT-67    MWH-2        31
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
47    AXCP-78    MWH-3        29
36    GCVB-79    MWH-2        28
2     LXCV-21    MWH-2        27
30    DDBN-89    MWH-4        27
34    GCVB-79    MWH-5        26
16    SDRT-67    MWH-5        12
8     GCVB-79    MWH-2        10

In [47]:
df2=df.sort_values(['MaterialID','Quantity']) #sorts on the provide column, check how to only sort on one specific values
df2

   MaterialID Location  Quantity
47    AXCP-78    MWH-3        29
4     AXCP-78    MWH-4        36
3     AXCP-78    MWH-5        65
37    AXCP-78    MWH-5        65
1     AXCP-78    MWH-1        67
38    AXCP-78    MWH-5        70
48    AXCP-78    MWH-1        75
46    AXCP-78    MWH-2        85
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152
30    DDBN-89    MWH-4        27
40    DDBN-89    MWH-1        34
43    DDBN-89    MWH-3        38
49    DDBN-89    MWH-1        39
22    DDBN-89    MWH-4        48
26    DDBN-89    MWH-1        57
45    DDBN-89    MWH-2        69
23    DDBN-89    MWH-5        71
8     GCVB-79    MWH-2        10
34    GCVB-79    MWH-5        26
36    GCVB-79    MWH-2        28
35    GCVB-79    MWH-2        31
15    GCVB-79    MWH-2        87
2     LXCV-21    MWH-2        27
28    LXCV-21    MWH-5        34
44    LXCV-21    MWH-3        42
29    LXCV-21    MWH-5        57
27    LXCV-21    MWH-5        83
16    SDRT-67    MWH-5        12
42    SDRT-67    MWH-2        31
10    SDRT-67    MWH-1        34
41    SDRT-67    MWH-1        57
11    SDRT-67    MWH-4        58
17    SDRT-67    MWH-5       102
7     TMI-43T    MWH-2        29
6     TMI-43T    MWH-4        31
13    TMI-43T    MWH-4        32
0     TMI-43T    MWH-4        34
18    TMI-43T    MWH-4        34
20    TMI-43T    MWH-4        39
32    TMI-43T    MWH-4        43
19    TMI-43T    MWH-4        52
14    TMI-43T    MWH-3        65
31    TMI-43T    MWH-4        65
21    TMI-43T    MWH-4        75
12    TMI-43T    MWH-4        76
5     TMI-43T    MWH-4        78
33    TMI-43T    MWH-5       112
9     TMI-43T    MWH-1       120

In [49]:
df2=df.sort_values(['Location','MaterialID','Quantity'],ascending=[True,True,False]) #you can give ascending values separate
df2

   MaterialID Location  Quantity
24    AXCP-78    MWH-1       152
39    AXCP-78    MWH-1       145
25    AXCP-78    MWH-1       109
48    AXCP-78    MWH-1        75
1     AXCP-78    MWH-1        67
26    DDBN-89    MWH-1        57
49    DDBN-89    MWH-1        39
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
10    SDRT-67    MWH-1        34
9     TMI-43T    MWH-1       120
46    AXCP-78    MWH-2        85
45    DDBN-89    MWH-2        69
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
8     GCVB-79    MWH-2        10
2     LXCV-21    MWH-2        27
42    SDRT-67    MWH-2        31
7     TMI-43T    MWH-2        29
47    AXCP-78    MWH-3        29
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
14    TMI-43T    MWH-3        65
4     AXCP-78    MWH-4        36
22    DDBN-89    MWH-4        48
30    DDBN-89    MWH-4        27
11    SDRT-67    MWH-4        58
5     TMI-43T    MWH-4        78
12    TMI-43T    MWH-4        76
21    TMI-43T    MWH-4        75
31    TMI-43T    MWH-4        65
19    TMI-43T    MWH-4        52
32    TMI-43T    MWH-4        43
20    TMI-43T    MWH-4        39
0     TMI-43T    MWH-4        34
18    TMI-43T    MWH-4        34
13    TMI-43T    MWH-4        32
6     TMI-43T    MWH-4        31
38    AXCP-78    MWH-5        70
3     AXCP-78    MWH-5        65
37    AXCP-78    MWH-5        65
23    DDBN-89    MWH-5        71
34    GCVB-79    MWH-5        26
27    LXCV-21    MWH-5        83
29    LXCV-21    MWH-5        57
28    LXCV-21    MWH-5        34
17    SDRT-67    MWH-5       102
16    SDRT-67    MWH-5        12
33    TMI-43T    MWH-5       112

In [51]:
b1=[9,40,80,120,160]
p1=['A','B','C','D']
df['Grade']=pd.cut(df.Quantity,bins=b1,labels=p1) #in this 40 will go  to lower category
df

   MaterialID Location  Quantity Grade
0     TMI-43T    MWH-4        34     A
1     AXCP-78    MWH-1        67     B
2     LXCV-21    MWH-2        27     A
3     AXCP-78    MWH-5        65     B
4     AXCP-78    MWH-4        36     A
5     TMI-43T    MWH-4        78     B
6     TMI-43T    MWH-4        31     A
7     TMI-43T    MWH-2        29     A
8     GCVB-79    MWH-2        10     A
9     TMI-43T    MWH-1       120     C
10    SDRT-67    MWH-1        34     A
11    SDRT-67    MWH-4        58     B
12    TMI-43T    MWH-4        76     B
13    TMI-43T    MWH-4        32     A
14    TMI-43T    MWH-3        65     B
15    GCVB-79    MWH-2        87     C
16    SDRT-67    MWH-5        12     A
17    SDRT-67    MWH-5       102     C
18    TMI-43T    MWH-4        34     A
19    TMI-43T    MWH-4        52     B
20    TMI-43T    MWH-4        39     A
21    TMI-43T    MWH-4        75     B
22    DDBN-89    MWH-4        48     B
23    DDBN-89    MWH-5        71     B
24    AXCP-78    MWH-1       152     D
25    AXCP-78    MWH-1       109     C
26    DDBN-89    MWH-1        57     B
27    LXCV-21    MWH-5        83     C
28    LXCV-21    MWH-5        34     A
29    LXCV-21    MWH-5        57     B
30    DDBN-89    MWH-4        27     A
31    TMI-43T    MWH-4        65     B
32    TMI-43T    MWH-4        43     B
33    TMI-43T    MWH-5       112     C
34    GCVB-79    MWH-5        26     A
35    GCVB-79    MWH-2        31     A
36    GCVB-79    MWH-2        28     A
37    AXCP-78    MWH-5        65     B
38    AXCP-78    MWH-5        70     B
39    AXCP-78    MWH-1       145     D
40    DDBN-89    MWH-1        34     A
41    SDRT-67    MWH-1        57     B
42    SDRT-67    MWH-2        31     A
43    DDBN-89    MWH-3        38     A
44    LXCV-21    MWH-3        42     B
45    DDBN-89    MWH-2        69     B
46    AXCP-78    MWH-2        85     C
47    AXCP-78    MWH-3        29     A
48    AXCP-78    MWH-1        75     B
49    DDBN-89    MWH-1        39     A

In [54]:
pune=pd.read_excel('CDAC_DataBook.xlsx',sheet_name='Pune')
mumbai=pd.read_excel('CDAC_DataBook.xlsx',sheet_name='Mumbai')

In [55]:
pune

      Name      Subject Grade
0   Rakesh       Python     A
1    Manoj     MLPython     C
2  Vaibhav   Statistics     B
3   Hitesh   CommSkills     A
4   Suyash  ProjectMgmt     B

In [56]:
mumbai

       Name     Subject Grade
0   Vaibhav   Six Sigma     A
1   Deepika  Statistics     B
2     Arjun  CommSkills     A
3    Chetan      Python     A
4  Abhishek    MLPython     B

In [58]:
pd.merge(pune,mumbai,on='Subject') #on is used to specified column that we want to take as common
#default value for "on" is all the subjects,for "how" that default value is inner

    Name_x     Subject Grade_x    Name_y Grade_y
0   Rakesh      Python       A    Chetan       A
1    Manoj    MLPython       C  Abhishek       B
2  Vaibhav  Statistics       B   Deepika       B
3   Hitesh  CommSkills       A     Arjun       A

In [59]:
pd.merge(pune,mumbai,on=['Subject','Grade']) #now it will take rows which are common in these both colmns

    Name_x     Subject Grade   Name_y
0   Rakesh      Python     A   Chetan
1  Vaibhav  Statistics     B  Deepika
2   Hitesh  CommSkills     A    Arjun

In [62]:
pd.merge(pune,mumbai,on=['Subject'],how="outer") #when we give how='outer' it takes common value, those are present in both

    Name_x      Subject Grade_x    Name_y Grade_y
0   Hitesh   CommSkills       A     Arjun       A
1    Manoj     MLPython       C  Abhishek       B
2   Suyash  ProjectMgmt       B       NaN     NaN
3   Rakesh       Python       A    Chetan       A
4      NaN    Six Sigma     NaN   Vaibhav       A
5  Vaibhav   Statistics       B   Deepika       B

In [63]:
pd.merge(pune,mumbai,on=['Subject'],how="left") #gives priority to pune take all rows from pune and give nan if that is not present in mumbai

    Name_x      Subject Grade_x    Name_y Grade_y
0   Rakesh       Python       A    Chetan       A
1    Manoj     MLPython       C  Abhishek       B
2  Vaibhav   Statistics       B   Deepika       B
3   Hitesh   CommSkills       A     Arjun       A
4   Suyash  ProjectMgmt       B       NaN     NaN

In [64]:
df=pd.read_excel("CDAC_DataBook.xlsx",sheet_name="Health")

In [76]:
df.head()

  Country Disease  2019  2020  2021
0   India  Cancer    12    94    35
1      UK  Cancer    95    19    84
2      US  Cancer    98    19    53
3   Japan  Cancer    89    52    14
4   India   Covid    38    19    62

In [78]:
df2=df.melt(id_vars=['Country','Disease'],var_name="Year",value_name="Cases")#id_var the colmn which i dont want to change,var_name=the name of new column,
#the column not present in id_vars is taken for adding in new coln, and values of that coln is stored in value_name

In [79]:
df2

   Country       Disease  Year  Cases
0    India        Cancer  2019     12
1       UK        Cancer  2019     95
2       US        Cancer  2019     98
3    Japan        Cancer  2019     89
4    India         Covid  2019     38
5       UK         Covid  2019     69
6       US         Covid  2019     87
7    Japan         Covid  2019     14
8    India  Heart Attack  2019     84
9       UK  Heart Attack  2019     44
10      US  Heart Attack  2019     34
11   Japan  Heart Attack  2019     11
12   India        Cancer  2020     94
13      UK        Cancer  2020     19
14      US        Cancer  2020     19
15   Japan        Cancer  2020     52
16   India         Covid  2020     19
17      UK         Covid  2020     73
18      US         Covid  2020     97
19   Japan         Covid  2020     12
20   India  Heart Attack  2020     10
21      UK  Heart Attack  2020     17
22      US  Heart Attack  2020     40
23   Japan  Heart Attack  2020     43
24   India        Cancer  2021     35
25      UK        Cancer  2021     84
26      US        Cancer  2021     53
27   Japan        Cancer  2021     14
28   India         Covid  2021     62
29      UK         Covid  2021     35
30      US         Covid  2021     35
31   Japan         Covid  2021     90
32   India  Heart Attack  2021     98
33      UK  Heart Attack  2021     24
34      US  Heart Attack  2021     54
35   Japan  Heart Attack  2021     75

In [92]:
#creating more columns,from the df  we use given commands

df3=df2.pivot_table(columns='Disease',values='Cases',index=['Country','Year']).reset_index().rename_axis(columns=None)
df3
#it creates new colns from disease and by taking values from cases and written in index will be unchanged, then reset index gives index from
#0 and then rename axis is used to --->

   Country  Year  Cancer  Covid  Heart Attack
0    India  2019    12.0   38.0          84.0
1    India  2020    94.0   19.0          10.0
2    India  2021    35.0   62.0          98.0
3    Japan  2019    89.0   14.0          11.0
4    Japan  2020    52.0   12.0          43.0
5    Japan  2021    14.0   90.0          75.0
6       UK  2019    95.0   69.0          44.0
7       UK  2020    19.0   73.0          17.0
8       UK  2021    84.0   35.0          24.0
9       US  2019    98.0   87.0          34.0
10      US  2020    19.0   97.0          40.0
11      US  2021    53.0   35.0          54.0

In [94]:
df=pd.read_excel('CDAC_DataBook.xlsx',sheet_name='ERPData')

In [103]:
df1=df.pivot_table(columns='Location',values='Quantity',index='MaterialID').reset_index().rename_axis(columns=None)

In [104]:
df1

  MaterialID       MWH-1  MWH-2  MWH-3      MWH-4       MWH-5
0    AXCP-78  109.600000   85.0   29.0  36.000000   66.666667
1    DDBN-89   43.333333   69.0   38.0  37.500000   71.000000
2    GCVB-79         NaN   39.0    NaN        NaN   26.000000
3    LXCV-21         NaN   27.0   42.0        NaN   58.000000
4    SDRT-67   45.500000   31.0    NaN  58.000000   57.000000
5    TMI-43T  120.000000   29.0   65.0  50.818182  112.000000

In [105]:
df1=df.pivot_table(columns='Location',values='Quantity',index='MaterialID').reset_index().rename_axis(columns=None)

In [106]:
df1=df.pivot_table(columns='Location',values='Quantity',index='MaterialID',aggfunc=sum).reset_index().rename_axis(columns=None)