In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
import os
os.getcwd()
os.chdir(r"C:\Users\athar\Downloads")

In [3]:
df=pd.read_excel('CDAC_DataBook.xlsx',sheet_name='ERPData')
df

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [4]:
df.MaterialID

0     TMI-43T
1     AXCP-78
2     LXCV-21
3     AXCP-78
4     AXCP-78
5     TMI-43T
6     TMI-43T
7     TMI-43T
8     GCVB-79
9     TMI-43T
10    SDRT-67
11    SDRT-67
12    TMI-43T
13    TMI-43T
14    TMI-43T
15    GCVB-79
16    SDRT-67
17    SDRT-67
18    TMI-43T
19    TMI-43T
20    TMI-43T
21    TMI-43T
22    DDBN-89
23    DDBN-89
24    AXCP-78
25    AXCP-78
26    DDBN-89
27    LXCV-21
28    LXCV-21
29    LXCV-21
30    DDBN-89
31    TMI-43T
32    TMI-43T
33    TMI-43T
34    GCVB-79
35    GCVB-79
36    GCVB-79
37    AXCP-78
38    AXCP-78
39    AXCP-78
40    DDBN-89
41    SDRT-67
42    SDRT-67
43    DDBN-89
44    LXCV-21
45    DDBN-89
46    AXCP-78
47    AXCP-78
48    AXCP-78
49    DDBN-89
Name: MaterialID, dtype: object

In [5]:
len(df.MaterialID)

50

In [6]:
np.unique(df.MaterialID)

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [7]:
mat_counts=df.MaterialID.value_counts().reset_index()
mat_counts

  MaterialID  count
0    TMI-43T     15
1    AXCP-78     11
2    DDBN-89      8
3    SDRT-67      6
4    LXCV-21      5
5    GCVB-79      5

In [8]:
df1=df.groupby(df.MaterialID)
df1.groups

{'AXCP-78': [1, 3, 4, 24, 25, 37, 38, 39, 46, 47, 48], 'DDBN-89': [22, 23, 26, 30, 40, 43, 45, 49], 'GCVB-79': [8, 15, 34, 35, 36], 'LXCV-21': [2, 27, 28, 29, 44], 'SDRT-67': [10, 11, 16, 17, 41, 42], 'TMI-43T': [0, 5, 6, 7, 9, 12, 13, 14, 18, 19, 20, 21, 31, 32, 33]}

In [9]:
mat_counts['Proportion']=mat_counts['count']/sum(mat_counts['count'])
mat_counts

  MaterialID  count  Proportion
0    TMI-43T     15        0.30
1    AXCP-78     11        0.22
2    DDBN-89      8        0.16
3    SDRT-67      6        0.12
4    LXCV-21      5        0.10
5    GCVB-79      5        0.10

In [10]:
mat_counts['Percentage']=mat_counts['count']*100/sum(mat_counts['count'])
mat_counts

  MaterialID  count  Proportion  Percentage
0    TMI-43T     15        0.30        30.0
1    AXCP-78     11        0.22        22.0
2    DDBN-89      8        0.16        16.0
3    SDRT-67      6        0.12        12.0
4    LXCV-21      5        0.10        10.0
5    GCVB-79      5        0.10        10.0

In [11]:
grades=np.array(['A','A','B','A','B','A','A','A','C','B','C'])

In [12]:
np.unique(grades,return_counts=True)

(array(['A', 'B', 'C'], dtype='<U1'), array([6, 3, 2], dtype=int64))

In [13]:
np.array([6,3,2])

array([6, 3, 2])

In [14]:
a=np.unique(grades,return_counts=True)

In [15]:
#proportion of cases in top 2 and top 3 states

In [16]:
df=pd.read_excel('covid_cases.xlsx')
df

  State  Cases
0    UP    250
1    KA    350
2    MH    650
3    KL    400
4    MP    350
5    AP    150
6    TG    100
7    TN    150

In [17]:
df["Prop"]=df['Cases']/sum(df['Cases'])
df #created the proportion

  State  Cases      Prop
0    UP    250  0.104167
1    KA    350  0.145833
2    MH    650  0.270833
3    KL    400  0.166667
4    MP    350  0.145833
5    AP    150  0.062500
6    TG    100  0.041667
7    TN    150  0.062500

In [18]:
df1=df.sort_values('Prop',ascending=False) #sets everything in descending order 
df1

  State  Cases      Prop
2    MH    650  0.270833
3    KL    400  0.166667
1    KA    350  0.145833
4    MP    350  0.145833
0    UP    250  0.104167
5    AP    150  0.062500
7    TN    150  0.062500
6    TG    100  0.041667

In [19]:
df2=np.cumsum(df1.Prop)  #we get cumsum ,ie step wise addition at each stage

In [20]:
df2.iloc[1] #gives the sum of first two values

0.4375

In [21]:
df2.iloc[2] #gives the sum of prop of first three position

0.5833333333333334

In [22]:
df=pd.read_excel('CDAC_DataBook.xlsx',sheet_name='faithful')
df

     eruptions  waiting
0        3.600       79
1        1.800       54
2        3.333       74
3        2.283       62
4        4.533       85
..         ...      ...
267      4.117       81
268      2.150       46
269      4.417       90
270      1.817       46
271      4.467       74

[272 rows x 2 columns]

In [23]:
erupt=df["eruptions"]

In [24]:
len(erupt)

272

In [25]:
sum(erupt)

948.677

In [26]:
sum(erupt)/len(erupt)

3.487783088235294

In [27]:
np.mean(erupt) #inbulit func to get mean

3.4877830882352936

In [28]:
df.eruptions.mean() #to get mean

3.4877830882352936

In [29]:
x1=np.sort(erupt)
x1[135]
x1[136]
#as here are even count of rows we are supposed to take 136,137 but as we are in python so we will take 135,136

4.0

In [30]:
marks={20:8,35:9,15:10}
df=np.array([[20,35,15],[8,9,10]])
df1=df[0]*df[1]

In [31]:
df2=df1.sum()

In [32]:
df3=df[0].sum()
df4=df2/df3
df4

8.928571428571429

In [33]:

df3

70

In [34]:
erupt

0      3.600
1      1.800
2      3.333
3      2.283
4      4.533
       ...
267    4.117
268    2.150
269    4.417
270    1.817
271    4.467
Name: eruptions, Length: 272, dtype: float64

In [35]:
erupt.mode()

0    1.867
1    4.500
Name: eruptions, dtype: float64

In [36]:
t=(np.where(erupt==1.867)[0]) #to extract the first value from array to show count we give[0]
len(t)

8

In [37]:
type(erupt)

pandas.core.series.Series

In [38]:
#range

In [39]:
t1=[1,1,2,2,3,3,3,3,4,4,4,4,4,4,5,5,5,5,5,6,6,6,6,6,7,7,7,7,7,7]
#find 25th percentile -1st quartile
# to find position we do,
#pos=1+(n-1)*percentile
pos=1+(len(t1)-1)*0.25
pos
t1[7] #==>3
t1[8] #==>4
percentile=3*0.75+4*0.25
percentile #==>manually calculated
np.percentile(t1,25) #inbulit function

3.25

In [40]:
pos

8.25

In [41]:
np.percentile(t1,80) #==>6.200000000000003 formula based
pos=1+(len(t1)-1)*0.8 #==>24.2
t1[23]#==>6
t1[24] #==>7
6*0.8+7*0.2 #== >6.200000000000001 manual calculation

6.200000000000001

In [42]:
np.percentile(t1,80)

6.200000000000003

In [43]:
#different quartile are 25th percentile==>first quartile,50th percentile==>2nd quartile or median,75th percentile==> 3rd quartile
#data from 25th per==>mean to 75th percentile==>max is mainly proper that removes all extreme values.

In [44]:
np.percentile(t1,90)#==>7.0
pos=1+(len(t1)-1)*90