In [6]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [7]:
import os
os.getcwd()
os.chdir(r"C:\Users\athar\Downloads")

In [8]:
df=pd.read_excel("CDAC_DataBook.xlsx",sheet_name='EmpInfo')
df

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN      NaN  ER534867
6   Deepak   NaN  Quality  RF453432

In [9]:
#one df--> values which are missing , and one df with clean df
ind=np.where(df.EmpID.isnull() | df.Deptt.isnull()) #either dept or emp id is null

In [10]:
df1=df.iloc[ind]

In [11]:
df1

     Name EmpID    Deptt  Passport
3   Arjun  A342      NaN  RF453432
5  Chetan   NaN      NaN  ER534867
6  Deepak   NaN  Quality  RF453432

In [157]:
df2=df.drop(ind[0])

In [158]:
df2

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
4    Rishi  R475    Prodn  DF453278

In [159]:
df=pd.read_excel("SalesData.xlsx")

In [160]:
df.head()

    Product     Category   Zone  Quantity  Unit_Price  Enquiries
0    Laptop  Electronics  North        10       55000       24.0
1     Mouse  Electronics  South        50         500       54.0
2  Keyboard  Electronics  North        20         900       37.0
3     Chair    Furniture  North         5        3000        NaN
4     Table    Furniture  North         2        7000       68.0

In [161]:
(df.isna())

    Product  Category   Zone  Quantity  Unit_Price  Enquiries
0     False     False  False     False       False      False
1     False     False  False     False       False      False
2     False     False  False     False       False      False
3     False     False  False     False       False       True
4     False     False  False     False       False      False
5     False     False   True     False       False      False
6     False     False  False     False       False       True
7     False     False  False     False       False       True
8     False     False  False     False       False      False
9     False     False  False     False       False      False
10    False     False  False     False       False      False
11    False     False   True     False       False      False
12    False     False  False     False       False      False
13    False     False  False     False       False      False
14    False     False   True     False       False       True
15    False     False   True     False       False      False
16    False     False  False     False       False      False
17    False     False  False     False       False      False
18    False     False   True     False       False      False
19    False     False  False     False       False      False
20    False     False   True     False       False      False
21    False     False  False     False       False      False

In [162]:
df['Enquiries']

0      24.0
1      54.0
2      37.0
3       NaN
4      68.0
5      58.0
6       NaN
7       NaN
8      46.0
9      24.0
10     68.0
11    154.0
12     68.0
13     32.0
14      NaN
15     30.0
16     45.0
17    108.0
18     32.0
19     15.0
20     40.0
21     68.0
Name: Enquiries, dtype: float64

In [163]:
df.head(5)

    Product     Category   Zone  Quantity  Unit_Price  Enquiries
0    Laptop  Electronics  North        10       55000       24.0
1     Mouse  Electronics  South        50         500       54.0
2  Keyboard  Electronics  North        20         900       37.0
3     Chair    Furniture  North         5        3000        NaN
4     Table    Furniture  North         2        7000       68.0

Question-1

In [164]:
df['Enquiries']=df.Enquiries.fillna(df.Enquiries.median())

In [165]:
df

       Product     Category   Zone  Quantity  Unit_Price  Enquiries
0       Laptop  Electronics  North        10       55000       24.0
1        Mouse  Electronics  South        50         500       54.0
2     Keyboard  Electronics  North        20         900       37.0
3        Chair    Furniture  North         5        3000       45.5
4        Table    Furniture  North         2        7000       68.0
5        Phone  Electronics    NaN        15       30000       58.0
6          Pen   Stationery  South       200          10       45.5
7     Notebook   Stationery  South       120          40       45.5
8   Headphones  Electronics  North        30        1500       46.0
9     Cupboard    Furniture   West         1       12000       24.0
10       Table    Furniture  North         2        7000       68.0
11      Bottle   Stationery    NaN        80          60      154.0
12     Charger  Electronics  North        40         800       68.0
13      Camera  Electronics  North         3       40000       32.0
14        Sofa    Furniture    NaN         1       45000       45.5
15         Bag   Stationery    NaN        30         300       30.0
16   Desk Lamp  Electronics  South        12        1200       45.0
17        File   Stationery  South        50          25      108.0
18     Printer  Electronics    NaN         4       15000       32.0
19       Shelf    Furniture   West         3        8000       15.0
20      Marker   Stationery    NaN        60          20       40.0
21     Charger  Electronics  North        40         800       68.0

In [166]:
df.Zone.mode()[0]

'North'

In [167]:
df['Zone']=df.Zone.fillna(df.Zone.mode()[0])

In [168]:
df.isnull().sum()

Product       0
Category      0
Zone          0
Quantity      0
Unit_Price    0
Enquiries     0
dtype: int64

Question-2

In [169]:
ind=np.where(df.duplicated())

In [170]:
df=df.drop(ind[0])

In [171]:
df

       Product     Category   Zone  Quantity  Unit_Price  Enquiries
0       Laptop  Electronics  North        10       55000       24.0
1        Mouse  Electronics  South        50         500       54.0
2     Keyboard  Electronics  North        20         900       37.0
3        Chair    Furniture  North         5        3000       45.5
4        Table    Furniture  North         2        7000       68.0
5        Phone  Electronics  North        15       30000       58.0
6          Pen   Stationery  South       200          10       45.5
7     Notebook   Stationery  South       120          40       45.5
8   Headphones  Electronics  North        30        1500       46.0
9     Cupboard    Furniture   West         1       12000       24.0
11      Bottle   Stationery  North        80          60      154.0
12     Charger  Electronics  North        40         800       68.0
13      Camera  Electronics  North         3       40000       32.0
14        Sofa    Furniture  North         1       45000       45.5
15         Bag   Stationery  North        30         300       30.0
16   Desk Lamp  Electronics  South        12        1200       45.0
17        File   Stationery  South        50          25      108.0
18     Printer  Electronics  North         4       15000       32.0
19       Shelf    Furniture   West         3        8000       15.0
20      Marker   Stationery  North        60          20       40.0

Create a new column with the name TotalPrice which should be a product of Quantity and Unit_Price.

In [172]:
x1=df['Quantity']*df['Unit_Price']

In [173]:
df['TotalPrice']=x1

In [174]:
df

,Product,Category,Zone,Quantity,Unit_Price,Enquiries,TotalPrice
0,Laptop,Electronics,North,10,55000,24.0,550000
1,Mouse,Electronics,South,50,500,54.0,25000
2,Keyboard,Electronics,North,20,900,37.0,18000
3,Chair,Furniture,North,5,3000,45.5,15000
4,Table,Furniture,North,2,7000,68.0,14000
5,Phone,Electronics,North,15,30000,58.0,450000
6,Pen,Stationery,South,200,10,45.5,2000
7,Notebook,Stationery,South,120,40,45.5,4800
8,Headphones,Electronics,North,30,1500,46.0,45000
9,Cupboard,Furniture,West,1,12000,24.0,12000
11,Bottle,Stationery,North,80,60,154.0,4800
12,Charger,Electronics,North,40,800,68.0,32000
13,Camera,Electronics,North,3,40000,32.0,120000
14,Sofa,Furniture,North,1,45000,45.5,45000
15,Bag,Stationery,North,30,300,30.0,9000
16,Desk Lamp,Electronics,South,12,1200,45.0,14400
17,File,Stationery,South,50,25,108.0,1250
18,Printer,Electronics,North,4,15000,32.0,60000
19,Shelf,Furniture,West,3,8000,15.0,24000
20,Marker,Stationery,North,60,20,40.0,1200

Create a new column with the name Code. The value in Code column should be A if the TotalPrice is more than 60000. If it is between 10000 and 60000 then the value in Code column should be B. The value should be C if the value in TotalPrice is less then 10000

In [175]:
Code=[]
list1=df['TotalPrice'].tolist()
for i in list1:
    if (i>60000):
        Code.append("A")
    elif(60000>i>10000):
        Code.append("B")
    else:
        Code.append("C")

In [176]:
df['Code']=Code

In [177]:
df

,Product,Category,Zone,Quantity,Unit_Price,Enquiries,TotalPrice,Code
0,Laptop,Electronics,North,10,55000,24.0,550000,A
1,Mouse,Electronics,South,50,500,54.0,25000,B
2,Keyboard,Electronics,North,20,900,37.0,18000,B
3,Chair,Furniture,North,5,3000,45.5,15000,B
4,Table,Furniture,North,2,7000,68.0,14000,B
5,Phone,Electronics,North,15,30000,58.0,450000,A
6,Pen,Stationery,South,200,10,45.5,2000,C
7,Notebook,Stationery,South,120,40,45.5,4800,C
8,Headphones,Electronics,North,30,1500,46.0,45000,B
9,Cupboard,Furniture,West,1,12000,24.0,12000,B
11,Bottle,Stationery,North,80,60,154.0,4800,C
12,Charger,Electronics,North,40,800,68.0,32000,B
13,Camera,Electronics,North,3,40000,32.0,120000,A
14,Sofa,Furniture,North,1,45000,45.5,45000,B
15,Bag,Stationery,North,30,300,30.0,9000,C
16,Desk Lamp,Electronics,South,12,1200,45.0,14400,B
17,File,Stationery,South,50,25,108.0,1250,C
18,Printer,Electronics,North,4,15000,32.0,60000,C
19,Shelf,Furniture,West,3,8000,15.0,24000,B
20,Marker,Stationery,North,60,20,40.0,1200,C

In [178]:
ind=np.where(df.TotalPrice>60000)
ind1=np.where((df.TotalPrice>10000) & (df.TotalPrice<60000))
ind2=np.where(df.TotalPrice<10000)


What are the products for which there have been more than 100 enquiries

In [179]:
ind4=np.where(df.Enquiries>100)
ind4
df2=df.iloc[ind4]
df2['Product']

11    Bottle
17      File
Name: Product, dtype: object

Which category has appeared most often in this dataset

In [12]:
df['Category'].mode()

KeyError: 'Category'

Which category has the largest number of enquiries

In [228]:
df['Enquiries'].max()
ind4=np.where(df.Enquiries==154)
df3=df.iloc[ind4]
df3['Category']

11    Stationery
Name: Category, dtype: object

In [ ]:
#doing without group by